/**
 * Created by hhly105 on 2015/9/28.
 */

var kjdetail = angular.module("live1.kjdetail", [
    "ngRoute",
    "ngResource",
    "ngCookies",
    "pascalprecht.translate"
]);
kjdetail.config(['$routeProvider', function ($routeProvider) {
    $routeProvider.when("/", {
        templateUrl: "/views/kjdetail_template/kjdetail_loading.html",
    }).when("/:kjId", {
        templateUrl: "/views/kjdetail_template/kjdetail_template.html",
        controller: "kjDetailController"
    }).otherwise({
        redirectTo: "/"
    });
}]);

kjdetail.config(["$translateProvider", function ($translateProvider) {
    var translationsEN = {
      "HEAD_TITLE":	"One Score Touchscreen Version",
      "LOTTERY_DETAILS":	"Lottery Draw Details",
      "LOTTERY_HISTORY":	"Historical Lottery Draw",
      "HONGKONG_LOTTERY":	"Hong Kong Lottery Draw",
      "SEVEN_COLOR":	"Seven-Color Lottery",
      "CHONGQING_CONSTANTCOLOR":	"Chongqing Instant Lottery",
      "BEIJING_CAR_RACING":	"Beijing Car Racing",
      "BEIJING_HAPPY_EI":	"Beijing Happy 8",
      "GUANGDONG_HAPPY_TEN":	"Guangdong Happy Lottery",
      "CHONGQING_LUCKY_FARM":	"Chongqing Lucky Farm",
      "JIANGXI_CONSTANTCOLOR":	"Jiangxi Instant Lottery",
      "XIJIANG_CONSTANTCOLOR":	"Xinjiang Instant Lottery",
      "HUNAN_HAPPY_TEN":	"Hunan Happy Lottery",
      "YUNNAN_CONSTANTCOLOR":	"Yunnan Instant Lottery",
      "TIANJIN_CONSTANTCOLOR":	"Tianjin Instant Lottery",
      "GUANGDONG_ElevenChooseFive":	"Guangdong 11 select 5",
      "JIANGSHU_ElevenChooseFive":	"Jiangsu 11 select 5",
      "SHANDONG_ElevenChooseFive":	"Shandong 11 select 5",
      "LIAONING_ElevenChooseFive":	"Liaoning 11 select 5",
      "JIANGXI_ElevenChooseFive":	"Jiangxi 11 select 5",
      "ANHUI_FASTTHREE":	"Anhui Fast 3",
      "GUANGXI_FASTTHREE":	"Guangxi Fast 3",
      "JIANGSHU_FASTTHREE":	"Jiangsu Fast 3",
      "CONSTANT_HAPPY":	"Instant Happy",
      "HUBEI_ElevenChooseFive":	"Hubei 11 select 5",
      "JILIN_HAPPY_THREE":	"Jilin Fast 3",
      "NO":	"Phase",
      "PERIOD":	"Period",
      "DRAGON":	"Dragon",
      "TIGER":	"Tiger",
      "RAT":	"Rat",
      "CATTLE":	"Cow",
      "RABBIT":	"Rabbit",
      "SNAKE":	"Snake",
      "HORSE":	"Horse",
      "MONKEY":	"Monkey",
      "SHEEP":	"Sheep",
      "CHICKEN":	"Chook",
      "DOG":	"Dog",
      "PIG":	"Pig",
      "SPEC":	"Special Number",
      "SUM":	"Total Points",
      "ZODIAC":	"Zodiac",
      "POULTRY_BEAST":	"Poultry & Beast",
      "POULTRY":	"Poultry",
      "BEAST":	"Beast",
      "TYPE":	"O/E",
      "MAX":	"O/U",
      "SPEC_COLOR":	"Color",
      "SCORE":	"Score",
      "DRAGON_TRIGER":	"Dragon/Tiger",
      "MANTISSA":	"Mantissa",
      "FIRST_BALL":	"1st Goal",
      "SECOND_BALL":	"2nd Goal",
      "THITD_BALL":	"3rd Goal",
      "FOURTH_BALL":	"4th Goal",
      "CHAMPION_SUM":	"Sum of No.1 & No.2",
      "CHAMPION":	"Champion",
      "SECOND":	"Runner-up",
      "THIRD":	"Third",
      "FOURTH":	"Fourth",
      "FIFTH":	"Fifth",
      "FITST_PLACE":	"No.1",
      "SECOND_PLACE":	"No.2",
      "FTHITD_PLACE":	"No.3",
      "FOURTH_PLACE":	"No.4",
      "FIFTH_PLACE":	"No.5",
      "SIXTH_PLACE":	"No.6",
      "SEVENTH_PLACE":	"No.7",
      "SMALL":	"Under",
      "BIG":	"Over",
      "SINGLE":	"Odd",
      "DOUBLE":	"Even",
      "EQUALS":	"Sum ",
      "RED":	"Red",
      "BLUE":	"Blue",
      "GREEN":	"Green",
      "SUNDAY":	"Sunday",
      "MONDAY":	"Monday",
      "TUESDAY":	"Tuesday",
      "WEDNESDAY":	"Wednesday",
      "THURSDAY":	"Thursday",
      "FRIDAY":	"Friday",
      "SATURDAY":	"Saturday",
      "ERROR_DAY":	"System error, unable to read date!",
      "LOADING":	"Loading",
      "ONLOADING":	"Loading hard...",
      "NO_DATA":	"No more lottery draw result"
    }
    var translationsZH = {
        "HEAD_TITLE": "一比分触屏版",
        "LOTTERY_DETAILS": "开奖详情",
        "LOTTERY_HISTORY": "历史开奖",
        "HONGKONG_LOTTERY": "香港开奖",
        "SEVEN_COLOR": "七星彩",
        "CHONGQING_CONSTANTCOLOR": "重庆时时彩",
        "BEIJING_CAR_RACING": "北京赛车",
        "BEIJING_HAPPY_EI": "北京快乐八",
        "GUANGDONG_HAPPY_TEN": "广东快乐十分",
        "CHONGQING_LUCKY_FARM": "重庆幸运农场",
        "JIANGXI_CONSTANTCOLOR": "江西时时彩",
        "XIJIANG_CONSTANTCOLOR": "新疆时时彩",
        "HUNAN_HAPPY_TEN": "湖南快乐十分",
        "YUNNAN_CONSTANTCOLOR": "云南时时彩",
        "TIANJIN_CONSTANTCOLOR": "天津时时彩",
        "GUANGDONG_ElevenChooseFive": "广东十一选五",
        "JIANGSHU_ElevenChooseFive": "江苏十一选五",
        "SHANDONG_ElevenChooseFive": "山东十一选五",
        "LIAONING_ElevenChooseFive": "辽宁十一选五",
        "JIANGXI_ElevenChooseFive": "江西十一选五",
        "ANHUI_FASTTHREE": "安徽快3",
        "GUANGXI_FASTTHREE": "广西快3",
        "JIANGSHU_FASTTHREE": "江苏快3",
        "CONSTANT_HAPPY": "时时乐",
        "HUBEI_ElevenChooseFive": "湖北十一选五",
        "JILIN_HAPPY_THREE": "吉林快3",
        "NO":"第",
        "PERIOD": "期",
        "DRAGON": "龙",
        "TIGER": "虎",
        "RAT": "鼠",
        "CATTLE": "牛",
        "RABBIT": "兔",
        "SNAKE": "蛇",
        "HORSE": "马",
        "MONKEY": "猴",
        "SHEEP": "羊",
        "CHICKEN": "鸡",
        "DOG": "狗",
        "PIG": "猪",
        "SPEC": "特码",
        "SUM": "总分",
        "ZODIAC": "生肖",
        "POULTRY_BEAST": "家/野",
        "POULTRY": "家禽",
        "BEAST": "野兽",
        "TYPE": "单双",
        "MAX": "大小",
        "SPEC_COLOR": "波色",
        "SCORE": "分值",
        "DRAGON_TRIGER": "龙虎",
        "MANTISSA":"尾数",
        "FIRST_BALL":"第一球",
        "SECOND_BALL":"第二球",
        "THITD_BALL":"第三球",
        "FOURTH_BALL":"第四球",
        "CHAMPION_SUM": "冠亚和",
        "CHAMPION": "冠军",
        "SECOND": "亚军",
        "THIRD": "第三名",
        "FOURTH": "第四名",
        "FIFTH": "第五名",
        "FITST_PLACE":"第一位",
        "SECOND_PLACE":"第二位",
        "FTHITD_PLACE":"第三位",
        "FOURTH_PLACE":"第四位",
        "FIFTH_PLACE":"第五位",
        "SIXTH_PLACE":"第六位",
        "SEVENTH_PLACE":"第七位",
        "SMALL": "小",
        "BIG": "大",
        "SINGLE": "单",
        "DOUBLE": "双",
        "EQUALS": "和",
        "RED": "红",
        "BLUE": "蓝",
        "GREEN": "绿",
        "SUNDAY": "星期日",
        "MONDAY": "星期一",
        "TUESDAY": "星期二",
        "WEDNESDAY": "星期三",
        "THURSDAY": "星期四",
        "FRIDAY": "星期五",
        "SATURDAY": "星期六",
        "ERROR_DAY": "系统错误，无法读取日期!",
        "LOADING": "加载中",
        "ONLOADING": "拼命加载中...",
        "NO_DATA": "已无更多彩果"
    };

    var translationsZH_HANS = {
        "HEAD_TITLE": "壹比分觸屏版",
        "LOTTERY_DETAILS": "開獎詳情",
        "LOTTERY_HISTORY": "歷史開獎",
        "HONGKONG_LOTTERY": "香港開獎",
        "SEVEN_COLOR": "七星彩",
        "CHONGQING_CONSTANTCOLOR": "重慶時時彩",
        "BEIJING_CAR_RACING": "北京賽車",
        "BEIJING_HAPPY_EI": "北京快樂八",
        "GUANGDONG_HAPPY_TEN": "廣東快樂十分",
        "CHONGQING_LUCKY_FARM": "重慶幸運農場",
        "JIANGXI_CONSTANTCOLOR": "江西時時彩",
        "XIJIANG_CONSTANTCOLOR": "新疆時時彩",
        "HUNAN_HAPPY_TEN": "湖南快樂十分",
        "YUNNAN_CONSTANTCOLOR": "雲南時時彩",
        "TIANJIN_CONSTANTCOLOR": "天津時時彩",
        "GUANGDONG_ElevenChooseFive": "廣東十一選五",
        "JIANGSHU_ElevenChooseFive": "江蘇十一選五",
        "SHANDONG_ElevenChooseFive": "山東十一選五",
        "HUBEI_ElevenChooseFive": "湖北十一選五",
        "LIAONING_ElevenChooseFive": "遼寧十一選五",
        "JIANGXI_ElevenChooseFive": "江西十一選五",
        "ANHUI_FASTTHREE": "安徽快3",
        "GUANGXI_FASTTHREE": "廣西快3",
        "JIANGSHU_FASTTHREE": "江蘇快3",
        "JILIN_HAPPY_THREE": "吉林快3",
        "CONSTANT_HAPPY": "時時樂",
        "NO":"第",
        "PERIOD": "期",
        "DRAGON": "龍",
        "TIGER": "虎",
        "RAT": "鼠",
        "CATTLE": "牛",
        "RABBIT": "兔",
        "SNAKE": "蛇",
        "HORSE": "馬",
        "MONKEY": "猴",
        "SHEEP": "羊",
        "CHICKEN": "雞",
        "DOG": "狗",
        "PIG": "豬",
        "SPEC": "特碼",
        "SUM": "總分",
        "ZODIAC": "生肖",
        "POULTRY_BEAST": "家/野",
        "POULTRY": "家禽",
        "BEAST": "野獸",
        "TYPE": "單雙",
        "MAX": "大小",
        "SPEC_COLOR": "波色",
        "SCORE": "分值",
        "DRAGON_TRIGER": "龍虎",
        "MANTISSA":"尾數",
        "FIRST_BALL":"第一球",
        "SECOND_BALL":"第二球",
        "THITD_BALL":"第三球",
        "FOURTH_BALL":"第四球",
        "CHAMPION_SUM": "冠亞和",
        "CHAMPION": "冠軍",
        "SECOND": "亞軍",
        "THIRD": "第三名",
        "FOURTH": "第四名",
        "FIFTH": "第五名",
        "FITST_PLACE":"第一位",
        "SECOND_PLACE":"第二位",
        "FTHITD_PLACE":"第三位",
        "FOURTH_PLACE":"第四位",
        "FIFTH_PLACE":"第五位",
        "SIXTH_PLACE":"第六位",
        "SEVENTH_PLACE":"第七位",
        "SMALL": "小",
        "BIG": "大",
        "SINGLE": "單",
        "DOUBLE": "雙",
        "EQUALS": "和",
        "RED": "紅",
        "BLUE": "藍",
        "GREEN": "綠",
        "SUNDAY": "週日",
        "MONDAY": "週一",
        "TUESDAY": "週二",
        "WEDNESDAY": "週三",
        "THURSDAY": "週四",
        "FRIDAY": "週五",
        "SATURDAY": "週六",
        "ERROR_DAY": "系統錯誤，無法讀取日期!",
        "LOADING": "加載中",
        "ONLOADING": "拼命加載中...",
        "NO_DATA": "已無更多彩果"
    }
    var translationsVI = {
      "HEAD_TITLE":"Tỷ Số Nhất bản màn hình cảm ứng",
      "LOTTERY_DETAILS":"Chi tiết xổ số",
      "LOTTERY_HISTORY":" Lịch sử xổ số",
      "HONGKONG_LOTTERY":"Xổ số HK",//"Xổ số HongKong ",
      "SEVEN_COLOR":"Xổ số bảy sao",
      "CHONGQING_CONSTANTCOLOR":"Xổ số liên tục Trùng Khánh",
      "BEIJING_CAR_RACING":"Đua xe Bắc Kinh",
      "BEIJING_HAPPY_EI":"Xổ số vui tám Bắc Kinh",
      "GUANGDONG_HAPPY_TEN":"Xổ số vui Quảng Đông",
      "CHONGQING_LUCKY_FARM":"Nông trừơng may mắn Trùng Khánh",
      "JIANGXI_CONSTANTCOLOR":"Xổ số liên tục Giang Tây",
      "XIJIANG_CONSTANTCOLOR":"Xổ số liên tục Tân Cương",
      "HUNAN_HAPPY_TEN":"Xổ số vui Hồ Nam",
      "YUNNAN_CONSTANTCOLOR":"Xổ số liên tục Vân Nam",
      "TIANJIN_CONSTANTCOLOR":"Xổ số liên tục Thiên Cân",
      "GUANGDONG_ElevenChooseFive":"11 chọn 5 Quảng Đông",
      "JIANGSHU_ElevenChooseFive":"11 chọn 5 Giang Tô",
      "SHANDONG_ElevenChooseFive":"11 chọn 5 Sơn Đông",
      "LIAONING_ElevenChooseFive":"11 chọn 5 Liêu Ninh",
      "JIANGXI_ElevenChooseFive":"11 chọn 5 Giang Tây",
      "ANHUI_FASTTHREE":"Nhanh 3 An Huy",
      "GUANGXI_FASTTHREE":"Nhanh 3 Quảng Tây",
      "JIANGSHU_FASTTHREE":"Nhanh 3 Giang Tô",
      "CONSTANT_HAPPY":"Vui liên tục",
      "HUBEI_ElevenChooseFive":"11 chọn 5 Hồ Bắc",
      "JILIN_HAPPY_THREE":"Nhanh 3 Cát Lâm",
      "NO":"Thứ",
      "PERIOD":"Kỳ",
      "DRAGON":"Rồng",
      "TIGER":"Hổ",
      "RAT":"Chuột",
      "CATTLE":"Bò",
      "RABBIT":"Thỏ",
      "SNAKE":"Rắn,",
      "HORSE":"Ngựa,",
      "MONKEY":"Khỉ",
      "SHEEP":"Cừu,",
      "CHICKEN":"Gà,",
      "DOG":"Chó,",
      "PIG":"Lợn,",
      "SPEC":"Số đặt biệt",
      "SUM":"Tổng",
      "Sinh tiêu":" Sinh tiêu",
      "POULTRY_BEAST":" Gia cầm / Dã thú",
      "POULTRY":" Gia cầm",
      "BEAST":"Dã thú",
      "TYPE":"Chẵn/Lẻ",
      "MAX":"Tài xỉu",
      "SPEC_COLOR":"Màu sắc",
      "SCORE":" Điểm",
      "DRAGON_TRIGER":"Rồng Hổ",
      "MANTISSA":"Số đuôi",
      "FIRST_BALL":"Goal thứ 1",
      "SECOND_BALL":"Goal thứ 2",
      "THITD_BALL":"Goal thứ 3",
      "FOURTH_BALL":"Goal thứ 4",
      "CHAMPION_SUM":"Số thứ 1 cộng số thứ 2",
      "CHAMPION":"Quán quân",
      "SECOND":"Á quân",
      "THIRD":"Thứ 3",
      "FOURTH":"Thứ 4",
      "FIFTH":"Thứ 5",
      "FITST_PLACE":"Vị thứ 1",
      "SECOND_PLACE":"Vị thứ 2",
      "FTHITD_PLACE":"Vị thứ 3",
      "FOURTH_PLACE":"Vị thứ 4",
      "FIFTH_PLACE":"Vị thứ 5",
      "SIXTH_PLACE":"Vị thứ 6",
      "SEVENTH_PLACE":"Vị thứ 7",
      "SMALL":"xỉu",
      "BIG":"Tài",
      "SINGLE":"Chẵn",
      "DOUBLE":"Lẻ",
      "EQUALS":"Tổng",
      "RED":"Đỏ",
      "BLUE":"Xanh dương ",
      "GREEN":"Xanh lá cây",
      "SUNDAY":"  Chủ nhật",
      "MONDAY":"  Thứ hai",
      "TUESDAY":"  Thứ ba",
      "WEDNESDAY":"  Thứ tư",
      "THURSDAY":"  Thứ năm",
      "FRIDAY":"  Thứ sáu",
      "SATURDAY":"  Thứ bảy",
      "ERROR_DAY":"Lỗi hệ thống, không có thể đọc ngày !",
      "LOADING":"Đang nạp",
      "ONLOADING":"Đang Loading nhanh...",
      "NO_DATA":"Không có nhiều kết quả xổ số"
    }
    var translationsTH = {
      "HEAD_TITLE":"วันสกอร์รุ่นหน้าจอสัมผัส ",
      "LOTTERY_DETAILS":"ดูรายละเอียด",//"รายละเอียดการออกผลล็อตเตอรี่",
      "LOTTERY_HISTORY":"ผลล็อตเตอรี่ย้อนหลัง",
      "HONGKONG_LOTTERY":"ล็อตเตอรี่ฮ่องกง",
      "SEVEN_COLOR":"ล็อตเตอรี่เจ็ดสี",
      "CHONGQING_CONSTANTCOLOR":"ฉงชิ่งจับสลากสด",
      "BEIJING_CAR_RACING":"การแข่งรถปักกิ่ง",
      "BEIJING_HAPPY_EI":"ล็อตเตอรี่ปักกิ่งแฮปปี้เบอร์ 8",
      "GUANGDONG_HAPPY_TEN":"กวางตุ้งล็อตเตอรี่แฮปปี้",
      "CHONGQING_LUCKY_FARM":"ฉงชิ่งลัคกี้ฟาร์ม",
      "JIANGXI_CONSTANTCOLOR":"เจียงซีจับสลากสด",
      "XIJIANG_CONSTANTCOLOR":"ซินเจียงจับสลากสด",
      "HUNAN_HAPPY_TEN":"หูหนานล็อตเตอรี่แฮปปี้",
      "YUNNAN_CONSTANTCOLOR":"ยูนนานจับสลากสด",
      "TIANJIN_CONSTANTCOLOR":"เทียนจีนจับสลากสด",
      "GUANGDONG_ElevenChooseFive":"กวางตุ้งสิบเอ็ดเลือกห้า",
      "JIANGSHU_ElevenChooseFive":"เจียงซูสิบเอ็ดเลือกห้า",
      "SHANDONG_ElevenChooseFive":"ซานตงสิบเอ็ดเลือกห้า",
      "LIAONING_ElevenChooseFive":"เหลียวหนิงสิบเอ็ดเลือกห้า",
      "JIANGXI_ElevenChooseFive":"เจียงซีสิบเอ็ดเลือกห้า",
      "ANHUI_FASTTHREE":"อานฮุยล็อตเตอรี่เบอร์ 3",
      "GUANGXI_FASTTHREE":"กวงซีล็อตเตอรี่เบอร์ 3",
      "JIANGSHU_FASTTHREE":"เจียงซูล็อตเตอรี่เบอร์ 3",
      "CONSTANT_HAPPY":"หวยทุกเวลา",
      "HUBEI_ElevenChooseFive":"หูหนานล็อตเตอรี่แฮปปี้",
      "JILIN_HAPPY_THREE":"จี๋หลินล็อตเตอรี่เบอร์ 3",
      "NO":"งวดที่",
      "PERIOD":"",
      "DRAGON":"มะโรง",
      "TIGER":"ขาล",
      "RAT":"ชวด",
      "CATTLE":"ฉลู",
      "RABBIT":"เถาะ",
      "SNAKE":"มะเส็ง",
      "HORSE":"มะเมีย",
      "MONKEY":"วอก",
      "SHEEP":"มะแม",
      "CHICKEN":"ระกา",
      "DOG":"จอ",
      "PIG":"กุน",
      "SPEC":"เลขพิเศษ",
      "SUM":"ผลเลขบวกกัน",
      "ZODIAC":"ราศี",
      "POULTRY_BEAST":"สัตว์ปีก/สัตว์ร้าย",
      "POULTRY":"สัตว์ปีก",
      "BEAST":"สัตว์ร้าย",
      "TYPE":"คี่คู่",
      "MAX":"สูงต่ำ",
      "SPEC_COLOR":"สีของหมายเลข",
      "SCORE":"ผลรวม",
      "DRAGON_TRIGER":"มะโรงและขาล",
      "MANTISSA":"เลขสุดท้าย",
      "FIRST_BALL":"ลูกแรก",
      "SECOND_BALL":"ลูกที่สอง",
      "THITD_BALL":"ลูกที่สาม",
      "FOURTH_BALL":"ลูกที่สี่",
      "CHAMPION_SUM":"ผลรวมเลขนแชมป์และรองชนะเลิศ",
      "CHAMPION":"แชมป์",
      "SECOND":"รองชนะเลิศ",
      "THIRD":"อันดับที่ 3",
      "FOURTH":"อันดับที่ 4",
      "FIFTH":"อันดับที่ 5",
      "FITST_PLACE":"เบอร์ 1",
      "SECOND_PLACE":"เบอร์ 2",
      "FTHITD_PLACE":"เบอร์ 3",
      "FOURTH_PLACE":"เบอร์ 4",
      "FIFTH_PLACE":"เบอร์ 5",
      "SIXTH_PLACE":"เบอร์ 6",
      "SEVENTH_PLACE":"เบอร์ 7",
      "SMALL":"ต่ำ",
      "BIG":"สูง",
      "SINGLE":"คี่",
      "DOUBLE":"คู่",
      "EQUALS":"ผลรวม",
      "RED":"สีแดง",
      "BLUE":"สีน้ำเงิน",
      "GREEN":"สีเขียว",
      "SUNDAY":"วันอาทิตย์",
      "MONDAY":"วันจันทร์",
      "TUESDAY":"วันอังคาร",
      "WEDNESDAY":"วันพุธ",
      "THURSDAY":"วันพฤหัสบดี",
      "FRIDAY":"วันศุกร์",
      "SATURDAY":"วันเสาร์",
      "ERROR_DAY":"เกิดข้อผิดพลาดในระบบ ไม่สามารถอ่านวันที่ได้",
      "LOADING":"กำลังโหลด",
      "ONLOADING":"กำลังพยายามโหลด",
      "NO_DATA":"ไม่มีผลล็อตเตอรี่ที่มากกว่านี้"
    }
    $translateProvider.translations('zh', translationsZH);
    $translateProvider.translations('zh-TW', translationsZH_HANS);
    $translateProvider.translations('en',translationsEN);
  $translateProvider.translations('th',translationsTH);
  $translateProvider.translations('vi',translationsVI);
  $translateProvider.registerAvailableLanguageKeys(['zh', 'zh-TW','en','th','vi'], {
    'zh_CN': 'zh',
    'zh_TW': 'zh-TW',
    'zh_HK': 'zh-TW',
    'en_US': 'en',
    'th_TH':'th',
    'vi_VI':'vi'
  });

    $translateProvider.useSanitizeValueStrategy(null);
    // try to find out preferred language by yourself
    //$translateProvider.determinePreferredLanguage();
    var language = window.localStorage.getItem("language");
    if (language == null) {
        language = defaultLanguageKey;
    }
    $translateProvider.preferredLanguage(language);
}]);



