/**
 * Created by john on 2015/9/24.
 */

var kjMain = angular.module("live1.kjmain", [
    "ngRoute",
    "ngResource",
    "pascalprecht.translate"
]);
var commonHeaderNav = ["$translateProvider", function ($translateProvider) {


  var i18n = {
    zh : {
      "nav_title": "一比分",
      "IMG_LOGO": "/images/zh/logo.png",
      "nav_basketball":"篮球比分",
      "nav_football":"足球比分",
      "nav_news" : "体育资讯",
      "nav_odds" : "足球指数",
      "nav_data" : "足球数据",
      "nav_basketdata": "篮球数据",
      "nav_video": "视频直播",
      "nav_kj":"彩票开奖",
      "nav_thcp": "泰国彩票"
    },
    en : {
      "nav_title":  "One Score",
      "IMG_LOGO": "/images/en/logo.png",
      "nav_basketball":"Basketball Score",
      "nav_football":"Football Score",
      "nav_news" : "Sports Information",
      "nav_odds" : "Football Odds",
      "nav_data" : "Football Data",
      "nav_basketdata": "Basketball Data",
      "nav_video": "Live Video",
      "nav_kj":"Lottery Draw",
      "nav_thcp":"lotto thai"
    },
    zh_hans: {
      "nav_title":"壹比分",
      "IMG_LOGO": "/images/zh-TW/logo.png",
      "nav_basketball":"籃球比分",
      "nav_football":"足球比分",
      "nav_news" : "體育資訊",
      "nav_odds" : "指數",
      "nav_data" : "足球數據",
      "nav_basketdata": "籃球數據",
      "nav_video": "視頻直播",
      "nav_kj":"彩票開獎",
      "nav_thcp":"泰國彩票"
    },
    th: {
      "nav_title":"วันสกอร์ ",
      "IMG_LOGO":"/images/th/logo.png",
      "nav_basketball":"สกอร์บาส",
      "nav_football":"สกอร์ฟุตบอล",
      "nav_news" : "หน้าแรก",
      "nav_odds" : "เปรียบเทียบอัตราต่อรอง",
      "nav_data" : "ข้อมูลฟุตบอล",
      "nav_basketdata": "ฐานข้อมูลบาส",
      "nav_video": "วิดีโอถ่ายทอดสด",
      "nav_kj":"การออกผลล็อตเตอรี่",
      "nav_thcp":"ผลสลากกินแบ่งรัฐบาล"
    },
    vi : {
      "nav_title":"Tỷ Số Nhất",
      "IMG_LOGO":"/images/vi/logo.png",
      "nav_basketball":"Tỷ số bóng rổ",
      "nav_football":"Tỷ số bóng đá",
      "nav_news" : "Tin tức thể thao",
      "nav_odds" : "Chỉ số bóng đá",
      "nav_data" : "Dữ liệu bóng đá",
      "nav_basketdata": "Dữ liệu bóng rổ",
      "nav_video": "Trực tiếp bóng đá",
      "nav_kj":"Xổ số",
      "nav_thcp":"lotto thai"
    }
  }
  $translateProvider.translations('zh', i18n.zh);
  $translateProvider.translations('zh-TW', i18n.zh_hans);
  $translateProvider.translations('en',i18n.en);
  $translateProvider.translations('th',i18n.th);
  $translateProvider.translations('vi',i18n.vi);

  $translateProvider.registerAvailableLanguageKeys(['zh', 'zh-TW','en','th','vi'], {
    'zh_CN': 'zh',
    'zh_TW': 'zh-TW',
    'zh_HK': 'zh-TW',
    'en_US':'en',
    'th':'th',
    'vi':'vi'
  });

  $translateProvider.useSanitizeValueStrategy(null);
  // try to find out preferred language by yourself
  //$translateProvider.determinePreferredLanguage();
  var language = window.localStorage.getItem("language");
  if (language == null) {
    language = defaultLanguageKey;
  }
  $translateProvider.preferredLanguage(language);
}]

kjMain.config(["$translateProvider", function ($translateProvider) {
    var translationsTH = {
      "HEAD_TITLE":"วันสกอร์รุ่นหน้าจอสัมผัส ",
      "LOTTERY_RESULTS":"ผลล็อตเตอรี่",
      "HOT_LOTTERY":"ล็อตเตอรี่นิยม",
      "HIGH_LOTTERY":"หวยความถี่สูง",
      "LOW_LOTTERY":"หวยความถี่ต่ำ",
      "NO":"งวดที่",
      "PERIOD":"Period",
      "CONFIRM":"ยืนยัน",
      'CANCEL' : "ยกเลิก",
      'FILTITLE':"ล็อตเตอรี่ของฉัน",
      'HAVEFILTITLE':"ล็อตเตอรี่ที่เลือก",
      "LOTTERY_TITLE":"ออกผลล็อตเตอรี่",
      "CLICK_FIL":"เลือกล็อตเตอรี่อื่น",
      "HONGKONG_LOTTERY":"ล็อตเตอรี่ฮ่องกง",
      "SEVEN_COLOR":"ล็อตเตอรี่เจ็ดสี",
      "SEVEN_COLOR_MARK":"ประกาศผลทุกวันอังคาร,วันศุกร์,วันอาทิตย์",
      "CHONGQING_CONSTANTCOLOR":"ฉงชิ่งจับสลากสด",
      "CHONGQINGCONSTANTCOLOR_MARK":"กลางวัน72เฟส,ทุก10นาที1เฟส；กลางคืน48เฟส,ทุก5นาที1เฟส",
      "BEIJING_CAR_RACING":"การแข่งรถปักกิ่ง",
      "BEIJINGCARRACING_MARK":"179เฟสต่อทุกวัน，ทุก5นาที1เฟส 9:00~00:00",
      "BEIJING_HAPPY_EI":"ล็อตเตอรี่ปักกิ่งแฮปปี้เบอร์ 8",
      "GUANGDONG_HAPPY_TEN":"กวางตุ้งล็อตเตอรี่แฮปปี้",
      "GUANGDONGHAPPYTEN_MARK":"84เฟสต่อทุกวัน，ทุก10นาที1เฟส，9:00~23:00",
      "CHONGQING_LUCKY_FARM":"ฉงชิ่งลัคกี้ฟาร์ม",
      "CHONGQINGLUCKYFARM_MARK":"97เฟสต่อทุกวัน，ทุก10นาที1เฟส，0:00-2:00 10:00-0:00",
      "JIANGXI_CONSTANTCOLOR":"เจียงซีจับสลากสด",
      "JIANGXICONSTANTCOLOR_MARK":"84เฟสต่อทุกวัน，ทุก10นาที1เฟส，9:00~23:00",
      "XIJIANG_CONSTANTCOLOR":"ซินเจียงจับสลากสด",
      "XIJIANGCONSTANTCOLOR_MARK":"96เฟสต่อทุกวัน，ทุก10นาที1เฟส，10:00~2:00",
      "HUNAN_HAPPY_TEN":"หูหนานล็อตเตอรี่แฮปปี้",
      "HUNANHAPPYTEN_MARK":"84เฟสต่อทุกวัน，ทุก10นาที1เฟส，9:00~23:00",
      "YUNNAN_CONSTANTCOLOR":"ยูนนานจับสลากสด",
      "YUNNANCONSTANTCOLOR_MARK":"72เฟสต่อทุกวัน，ทุก10นาที1เฟส，10:00~21:50",
      "TIANJIN_CONSTANTCOLOR":"เทียนจีนจับสลากสด",
      "TIANJINCONSTANTCOLOR_MARK":"84 รอบทุกวัน ทุก 10 นาที่หนึ่งรอบ 9:00~23:00",
      "GUANGDONG_ElevenChooseFive":"กวางตุ้งสิบเอ็ดเลือกห้า",
      "GUANGDONGElevenChooseFive_MARK":"84เฟสต่อทุกวัน，ทุก10นาที1เฟส，9:00~23:00",
      "JIANGSHU_ElevenChooseFive":"เจียงซูสิบเอ็ดเลือกห้า",
      "JIANGSHUElevenChooseFive_MARK":"82เฟสต่อทุกวัน，ทุก10นาที1เฟส，8:30~22:10",
      "SHANDONG_ElevenChooseFive":"ซานตงสิบเอ็ดเลือกห้า",
      "SHANDONGElevenChooseFive_MARK":"78เฟสต่อทุกวัน，ทุก10นาที1เฟส 9:00-22:00",
      "LIAONING_ElevenChooseFive":"เหลียวหนิงสิบเอ็ดเลือกห้า",
      "JIANGXI_ElevenChooseFive":"เจียงซีสิบเอ็ดเลือกห้า",
      "ANHUI_FASTTHREE":"อานฮุยล็อตเตอรี่เบอร์ 3",
      "ANHUIFASTTHREE_MARK":"80เฟสต่อทุกวัน，ทุก10นาที1เฟส，8:30~22:00",
      "GUANGXI_FASTTHREE":"กวงซีล็อตเตอรี่เบอร์ 3",
      "GUANGXIFASTTHREE_MARK":"78เฟสต่อทุกวัน，ทุก10นาที1เฟส ，9:30-22:30",
      "JIANGSHU_FASTTHREE":"เจียงซูล็อตเตอรี่เบอร์ 3",
      "JIANGSHUFASTTHREE_MARK":"82เฟสต่อทุกวัน，ทุก10นาที1เฟส，8:30~22:00",
      "CONSTANT_HAPPY":"หวยทุกเวลา",
      "HUBEI_ElevenChooseFive":"หูหนานล็อตเตอรี่แฮปปี้",
      "JILIN_HAPPY_THREE":"จี๋หลินล็อตเตอรี่เบอร์ 3",
      "SUM":"คะแนนรวม",
      "SUM_MAX":"คะแนนรวมสูงต่ำ",
      "SUM_TYPE":"คะแนนรวมคี่คู่",
      "DRAGON_TRIGER":"มะโรงและขาล",
      "SPEC_MAX":"สูงต่ำเลขพิเศษ",
      "SPEC_TYPE":"คี่คู่เลขพิเศษ",
      "SPEC_COLOR":"สีของเลขท้าย",
      "SUM_LAST_MAX":"สูงต่ำผลรวมเลขท้าย",
      "SUM_RESULT":"ผลเลขรวม",
      "SUM_NUM":"สูงต่ำผลเลขรวม",
      "SUM_SINGLE":"คี่คู่ผลเลขรวม",
      "SUM_WEI":"สูงต่ำผลรวมเลขท้าย",
      "CHAMPION":"แชมป์",
      "SECOND":"รองชนะเลิศ",
      "CHAMPION_SUM":"ผลเลขแชมป์บวกเลขรองชนะเลิศ",
      "CHAMPION_TYPE":"คี่คู่ผลรวมเลขแชมป์และรองชนะเลิศ",
      "TIME_COUNT_DOWN":"นับถอยหลังการออกผลล็อตเตอรี่",
      "OPENING":"กำลังออกผล",
      "LOADING":"กำลังโหลด",
      "ONLOADING":"กำลังพยายามโหลด",
      "SCOLL_PAGE":"เลื่อนลงเพื่อโหลดข้อมูลโดยอัตโนมัติ",
      "NO_DATA":"ไม่มีผลล็อตเตอรี่ที่มากกว่านี้",
      "NO_CHOICE":"ยังไม่มีล็อตเตอรี่ของฉัน",
      "SMALL":"ต่ำ",
      "BIG":"สูง",
      "SINGLE":"เลขเดี่ยว",
      "DOUBLE":"เลขคู่",
      "EQUALS":"เสมอ",
      "DRAGON":"มะโรง",
      "TIGER":"ขาล",
      "RAT":"ชวด",
      "CATTLE":"ฉลู",
      "RABBIT":"เถาะ",
      "SNAKE":"มะเส็ง",
      "HORSE":"มะเมีย",
      "MONKEY":"วอก",
      "SHEEP":"มะแม",
      "CHICKEN":"ระกา",
      "DOG":"จอ",
      "PIG":"กุน",
      "RED":"สีแดง",
      "BLUE":"สีฟ้า",
      "GREEN":"สีเขียว"
    }
    var translationsEN = {
      "HEAD_TITLE":	"One Score Touchscreen Version ",
      "LOTTERY_RESULTS":	"Results",
      "HOT_LOTTERY":	"Hot Lotteries",
      "HIGH_LOTTERY":	"High Frequence Lottery",
      "LOW_LOTTERY":	"Low Frequence Lottery",
      "NO":	"Phase",
      "PERIOD":	"Period",
      "CONFIRM":	"Confirm",
      'CANCEL':	"Cancel",
      'FILTITLE':	"Customized Lottery",
      'HAVEFILTITLE':	"Have customized lottery",
      "LOTTERY_TITLE":	"Lottery Draw",
      "CLICK_FIL":	"Click to customize more lotteries",
      "HONGKONG_LOTTERY":	"HK Lottery Draw",
      "SEVEN_COLOR":	"Seven-Color Lottery",
      "SEVEN_COLOR_MARK":	"Lottery Draw at 20:30 on every Tuesday, Friday and Sunday",
      "CHONGQING_CONSTANTCOLOR":	"Chongqing Instant Lottery",
      "CHONGQINGCONSTANTCOLOR_MARK":	"Daytime 72 phases, 1 phase per 10 minutes; Night 48 phases, 1 phase per 5 minutes",
      "BEIJING_CAR_RACING":	"Beijing Car Racing",
      "BEIJINGCARRACING_MARK":	"179 phases everyday, 1 phase per 5 minutes, 9:00-00:00",
      "BEIJING_HAPPY_EI":	"Beijing Happy 8",
      "GUANGDONG_HAPPY_TEN":	"Guangdong Happy Lottery",
      "GUANGDONGHAPPYTEN_MARK":	"84 phases everyday, 1 phase per 10 minutes, 9:00-23:00",
      "CHONGQING_LUCKY_FARM":	"Chongqing Lucky Farm",
      "CHONGQINGLUCKYFARM_MARK":	"97 phases everyday, 1 phase per 10 minutes, 0:00-2:00 10:00-0:00",
      "JIANGXI_CONSTANTCOLOR":	"Jiangxi Instant Lottery",
      "JIANGXICONSTANTCOLOR_MARK":	"84 phases everyday, 1 phase per 10 minutes, 9:00-23:00",
      "XIJIANG_CONSTANTCOLOR":	"Xinjiang Instant Lottery",
      "XIJIANGCONSTANTCOLOR_MARK":	"96 phases everyday, 1 phase per 10 minutes, 10:00-2:00",
      "HUNAN_HAPPY_TEN":	"Hunan Happy Lottery",
      "HUNANHAPPYTEN_MARK":	"84 phases everyday, 1 phase per 10 minutes, 9:00-23:00",
      "YUNNAN_CONSTANTCOLOR":	"Yunnan Instant Lottery",
      "YUNNANCONSTANTCOLOR_MARK":	"72 phases everyday, 1 phase per 10 minutes, 10:00-21:50",
      "TIANJIN_CONSTANTCOLOR":	"Tianjin Instant Lottery",
      "TIANJINCONSTANTCOLOR_MARK":	"84 phases everyday, 1 phase per 10 minutes, 9:00-23:00",
      "GUANGDONG_ElevenChooseFive":	"Guangdong 11 select 5",
      "GUANGDONGElevenChooseFive_MARK":	"84 phases everyday, 1 phase per 10 minutes, 9:00-23:00",
      "JIANGSHU_ElevenChooseFive":	"Jiangsu 11 select 5",
      "JIANGSHUElevenChooseFive_MARK":	"82 phases everyday, 1 phase per 10 minutes, 8:30-22:10",
      "SHANDONG_ElevenChooseFive":	"Shandong 11 select 5",
      "SHANDONGElevenChooseFive_MARK":	"78 phases everyday, 1 phase per 10 minutes, 9:00-22:00",
      "LIAONING_ElevenChooseFive":	"Liaoning 11 select 5",
      "JIANGXI_ElevenChooseFive":	"Jiangxi 11 select 5",
      "ANHUI_FASTTHREE":	"Anhui Fast 3",
      "ANHUIFASTTHREE_MARK":	"80 phases everyday, 1 phase per 10 minutes, 8:30-22:00",
      "GUANGXI_FASTTHREE":	"Guangxi Fast 3",
      "GUANGXIFASTTHREE_MARK":	"78 phases everyday, 1 phase per 10 minutes, 9:30-22:30",
      "JIANGSHU_FASTTHREE":	"Jiangsu Fast 3",
      "JIANGSHUFASTTHREE_MARK":	"82 phases everyday, 1 phase per 10 minutes, 8:30-22:00",
      "CONSTANT_HAPPY":	"Instant Happy",
      "HUBEI_ElevenChooseFive":	"Hubei 11 select 5",
      "JILIN_HAPPY_THREE":	"Jilin Fast 3",
      "SUM":	"Total Points",
      "SUM_MAX":	"Total Points O/U",
      "SUM_TYPE":	"Total Points O/E",
      "DRAGON_TRIGER":	"Dragon/Tiger",
      "SPEC_MAX":	"Special Number O/U",
      "SPEC_TYPE":	"Special Number O/E",
      "SPEC_COLOR":	"Special Number Color",
      "SUM_LAST_MAX":	"Sum Mantissa O/U",
      "SUM_RESULT":	"Sum Value",
      "SUM_NUM":	"Sum Value O/U",
      "SUM_SINGLE":	"Sum Value O/E",
      "SUM_WEI":	"Sum Mantissa O/U",
      "CHAMPION":	"Champion",
      "SECOND":	"Runner-up",
      "CHAMPION_SUM":	"Sum of No.1 & No.2 O/U",
      "CHAMPION_TYPE":	"Sum of No.1 & No.2 O/E",
      "TIME_COUNT_DOWN":	"Lottery Draw Countdown",
      "OPENING":	"In Lottery Draw…",
      "LOADING":	"Loading",
      "ONLOADING":	"Loading hard...",
      "SCOLL_PAGE":	"Pull down to load automatically",
      "NO_DATA":	"No more lottery draw result",
      "NO_CHOICE":	"Have no customized lottery",
      "SMALL":	"Under",
      "BIG":	"Over",
      "SINGLE":	"Odd",
      "DOUBLE":	"Even",
      "EQUALS":	"Sum",
      "DRAGON":	"Dragon",
      "TIGER":	"Tiger",
      "RAT":	"Rat",
      "CATTLE":	"Cow",
      "RABBIT":	"Rabbit",
      "SNAKE":	"Snake",
      "HORSE":	"Horse",
      "MONKEY":	"Monkey",
      "SHEEP":	"Sheep",
      "CHICKEN":	"Chook",
      "DOG":	"Dog",
      "PIG":	"Pig",
      "RED":	"Red",
      "BLUE":	"Blue",
      "GREEN":	"Green"
    }
    var translationsZH = {
        "HEAD_TITLE": "一比分触屏版",
        "LOTTERY_RESULTS": "开奖结果",
        "HOT_LOTTERY": "热门彩种",
        "HIGH_LOTTERY": "高频彩",
        "LOW_LOTTERY": "低频彩",
        "NO":"第",
        "PERIOD": "期",
        "CONFIRM": '确定',
        'CANCEL': '取消',
        'FILTITLE': '定制彩种',
        'HAVEFILTITLE': '已定制彩种',
        "LOTTERY_TITLE": "彩票开奖",
        "CLICK_FIL": '点击定制更多彩种',
        "HONGKONG_LOTTERY": "香港开奖",
        "SEVEN_COLOR": "七星彩",
        "SEVEN_COLOR_MARK": "每周二、五、日晚20:30开奖",
        "CHONGQING_CONSTANTCOLOR": "重庆时时彩",
        "CHONGQINGCONSTANTCOLOR_MARK": "白天72期，10分钟一期；晚上48期，5分钟一期",
        "BEIJING_CAR_RACING": "北京赛车",
        "BEIJINGCARRACING_MARK":"每天179期，5分钟一期，9:00~00:00",
        "BEIJING_HAPPY_EI": "北京快乐八",
        "GUANGDONG_HAPPY_TEN": "广东快乐十分",
        "GUANGDONGHAPPYTEN_MARK": "每天84期，10分钟一期，9:00~23:00",
        "CHONGQING_LUCKY_FARM": "重庆幸运农场",
        "CHONGQINGLUCKYFARM_MARK": "每天97期，10分钟一期，0:00~2:00 10:00~0:00",
        "JIANGXI_CONSTANTCOLOR": "江西时时彩",
        "JIANGXICONSTANTCOLOR_MARK": "每天84期，10分钟一期，9:00~23:00",
        "XIJIANG_CONSTANTCOLOR": "新疆时时彩",
        "XIJIANGCONSTANTCOLOR_MARK": "每天96期，10分钟一期，10:00~2:00",
        "HUNAN_HAPPY_TEN": "湖南快乐十分",
        "HUNANHAPPYTEN_MARK": "每天84期，10分钟一期，9:00~23:00",
        "YUNNAN_CONSTANTCOLOR": "云南时时彩",
        "YUNNANCONSTANTCOLOR_MARK": "每天72期，10分钟一期，10:00~21:50",
        "TIANJIN_CONSTANTCOLOR": "天津时时彩",
        "TIANJINCONSTANTCOLOR_MARK": "每天84期，10分钟一期，9:00~23:00",
        "GUANGDONG_ElevenChooseFive": "广东十一选五",
        "GUANGDONGElevenChooseFive_MARK": "每天84期，10分钟一期，9:00~23:00",
        "JIANGSHU_ElevenChooseFive": "江苏十一选五",
        "JIANGSHUElevenChooseFive_MARK": "每天82期，10分钟一期，8:30~22:10",
        "SHANDONG_ElevenChooseFive": "山东十一选五",
        "SHANDONGElevenChooseFive_MARK": "每天78期，10分钟一期，9:00~22:00",
        "LIAONING_ElevenChooseFive": "辽宁十一选五",
        "JIANGXI_ElevenChooseFive": "江西十一选五",
        "ANHUI_FASTTHREE": "安徽快3",
        "ANHUIFASTTHREE_MARK": "每天80期，10分钟一期，8:30~22:00",
        "GUANGXI_FASTTHREE": "广西快3",
        "GUANGXIFASTTHREE_MARK": "每天78期，10分钟一期，9:30~22:30",
        "JIANGSHU_FASTTHREE": "江苏快3",
        "JIANGSHUFASTTHREE_MARK": "每天82期，10分钟一期，8:30~22:00",
        "CONSTANT_HAPPY": "时时乐",
        "HUBEI_ElevenChooseFive": "湖北十一选五",
        "JILIN_HAPPY_THREE": "吉林快3",
        "SUM": "总分",
        "SUM_MAX": "总分大小",
        "SUM_TYPE": "总分单双",
        "DRAGON_TRIGER": "龙虎",
        "SPEC_MAX": "特码大小",
        "SPEC_TYPE": "特码单双",
        "SPEC_COLOR": "特码波色",
        "SUM_LAST_MAX": "总和尾数大小",
        "SUM_RESULT": "和值",
        "SUM_NUM": "和值大小",
        "SUM_SINGLE": "和值单双",
        "SUM_WEI": "和尾大小",
        "CHAMPION": "冠军",
        "SECOND": "亚军",
        "CHAMPION_SUM": "冠亚和大小",
        "CHAMPION_TYPE": "冠亚和单双",
        "TIME_COUNT_DOWN": "开奖倒计时",
        "OPENING": "正在开奖中...",
        "LOADING": "加载中",
        "ONLOADING": "拼命加载中...",
        "SCOLL_PAGE": "页面下拉自动加载内容",
        "NO_DATA": "已无更多彩果",
        "NO_CHOICE":"用户没有定制彩种",
        "SMALL": "小",
        "BIG": "大",
        "SINGLE": "单",
        "DOUBLE": "双",
        "EQUALS": "和",
        "DRAGON": "龙",
        "TIGER": "虎",
        "RAT": "鼠",
        "CATTLE": "牛",
        "RABBIT": "兔",
        "SNAKE": "蛇",
        "HORSE": "马",
        "MONKEY": "猴",
        "SHEEP": "羊",
        "CHICKEN": "鸡",
        "DOG": "狗",
        "PIG": "猪",
        "RED": "红",
        "BLUE": "蓝",
        "GREEN": "绿"

    };
    var translationsVI = {
      "HEAD_TITLE":"Tỷ Số Nhất bản màn hình cảm ứng",
      "LOTTERY_RESULTS":"Kết quả giải thưởng",
      "HOT_LOTTERY":"Xổ số nóng",
      "HIGH_LOTTERY":"Xổ số cao tần",
      "LOW_LOTTERY":"Xổ số tần suất thấp",
      "NO":"thứ",
      "PERIOD":"kỳ",
      "CONFIRM":"OK",
      'CANCEL': 	"hủy",
      'FILTITLE' :	"Đặt xổ số",
      'HAVEFILTITLE': 	"Đã đặt",
      "LOTTERY_TITLE":"giải thưởng",
      "CLICK_FIL":"Click để đặt thêm",
      "HONGKONG_LOTTERY":"Xổ số HK",
      "SEVEN_COLOR":"Xổ số bảy sao",
      "SEVEN_COLOR_MARK":"Mỗi tuần 20:30 thứ ba,sáu,chủ nhật giải thường",
      "CHONGQING_CONSTANTCOLOR":"Xổ số Shishi Trùng Khánh",//"Xổ số liên tục Trùng Khánh",
      "CHONGQINGCONSTANTCOLOR_MARK":"Ban ngày có 72 kỳ,10 phút một kỳ :buổi tối 48 kỳ,5 phút một kỳ",
      "BEIJING_CAR_RACING":"Đua xe Bắc Kinh",
      "BEIJINGCARRACING_MARK":"Mõi ngày 179 kỳ,5 phút một kỳ,9:00~00:00",
      "BEIJING_HAPPY_EI":"Xổ số vui Bắc Kinh",
      "GUANGDONG_HAPPY_TEN":"Xổ số vui Quảng Đông",
      "GUANGDONGHAPPYTEN_MARK":"Mõi ngày 84 kỳ,10 phút một kỳ,9:00~23:00",
      "CHONGQING_LUCKY_FARM":"Nôngtrừơng TrùngKhánh",//"Nông trừơng Trùng Khánh",//"Nông trừơng may mắn Trùng Khánh",
      "CHONGQINGLUCKYFARM_MARK":"Mõi ngày 97 kỳ,10 phút một kỳ,0:00~2:00 10:00~0:00",
      "JIANGXI_CONSTANTCOLOR":"Xổ số liên tục Giang Tây",
      "JIANGXICONSTANTCOLOR_MARK":"Mõi ngày 84 kỳ,10 phút một kỳ,9:00~23:00",
      "XIJIANG_CONSTANTCOLOR":"Xổ số liên tục Tân Cương",
      "XIJIANGCONSTANTCOLOR_MARK":"Mõi ngày 96 kỳ,10 phút một kỳ,10:00~2:00",
      "HUNAN_HAPPY_TEN":"Xổ số vui Hồ Nam",
      "HUNANHAPPYTEN_MARK":"Mõi ngày 84 kỳ,10 phút một kỳ,9:00~23:00",
      "YUNNAN_CONSTANTCOLOR":"Xổ số liên tục Vân Nam",
      "YUNNANCONSTANTCOLOR_MARK":"Mõi ngày 72 kỳ,10 phút một kỳ,10:00~21:50",
      "TIANJIN_CONSTANTCOLOR":"Xổ số liên tục Thiên Cân",
      "TIANJINCONSTANTCOLOR_MARK":"Mõi ngày 84 kỳ,10 phút một kỳ,9:00~23:00",
      "GUANGDONG_ElevenChooseFive":"11 chọn 5 Quảng Đông",
      "GUANGDONGElevenChooseFive_MARK":"Mõi ngày 84 kỳ,10 phút một kỳ,9:00~23:00",
      "JIANGSHU_ElevenChooseFive":"11 chọn 5 Giang Tô",
      "JIANGSHUElevenChooseFive_MARK":"Mõi ngày 82 kỳ,10 phút một kỳ,8:30~22:10",
      "SHANDONG_ElevenChooseFive":"11 chọn 5 Sơn Đông",
      "SHANDONGElevenChooseFive_MARK":"Mõi ngày 78 kỳ,10 phút một kỳ,9:00~22:00",
      "LIAONING_ElevenChooseFive":"11 chọn 5 Liêu Ninh",
      "JIANGXI_ElevenChooseFive":"11 chọn 5 Giang Tây",
      "ANHUI_FASTTHREE":"Nhanh 3 An Huy",
      "ANHUIFASTTHREE_MARK":"Mõi ngày 80 kỳ,10 phút một kỳ,8:30~22:00",
      "GUANGXI_FASTTHREE":"Nhanh 3 Quảng Tây",
      "GUANGXIFASTTHREE_MARK":"Mõi ngày 78 kỳ,10 phút một kỳ,9:30~22:30",
      "JIANGSHU_FASTTHREE":"Nhanh 3 Giang Tô",
      "JIANGSHUFASTTHREE_MARK":"Mõi ngày 82 kỳ,10 phút một kỳ,8:30~22:00",
      "CONSTANT_HAPPY":"Vui liên tục",
      "HUBEI_ElevenChooseFive":"11 chọn 5 Hồ Nam",
      "JILIN_HAPPY_THREE":"Nhanh 3 Cát Lâm",
      "SUM":"Tổng",
      "SUM_MAX":"Tổng tài xỉu",
      "SUM_TYPE":"Tổng chẵn/Lẻ",
      "DRAGON_TRIGER":"Rồng Hổ",
      "SPEC_MAX":"Số  đặc biệt tài xỉu",
      "SPEC_TYPE":"Số  đặc biệt chẵn/Lẻ",
      "SPEC_COLOR":"Số  đặc biệt màu sắc",
      "SUM_LAST_MAX":"Tống số đuôi tài xỉu",
      "SUM_RESULT":"Tống ",
      "SUM_NUM":"Tống số đuôi tài xỉu",
      "SUM_SINGLE":"Tống số đuôi chẵn/Lẻ",
      "SUM_WEI":"tống số đuôi tài xỉu",
      "CHAMPION":"Quán quân",
      "SECOND":"Á quân",
      "CHAMPION_SUM":"Tài xỉu số thứ 1 cộng số thứ 2",
      "CHAMPION_TYPE":"Chẵn/Lẻ số thứ 1 cộng số thứ 2",
      "TIME_COUNT_DOWN":"Đếm  ngược mở thưởng",
      "OPENING":"Đang giải thưởng",
      "LOADING":"Đang cập nhật",
      "ONLOADING":"Đang cố cập nhật nhanh...",
      "SCOLL_PAGE":"Thả xuống trang tự động cập nhật nội dung",
      "NO_DATA":"Không có nhiều kết quả xổ số",
      "NO_CHOICE":"Người sử dụng chưa đặt xổ số",
      "SMALL":"xỉu",
      "BIG":"tài",
      "SINGLE":"chẵn",
      "DOUBLE":"lẻ",
      "EQUALS":"tỏng",
      "DRAGON":"Rồng",
      "TIGER":"Hổ",
      "RAT":"Chuột",
      "CATTLE":"Bò",
      "RABBIT":"Thỏ",
      "SNAKE":"Rắn,",
      "HORSE":"Ngựa,",
      "MONKEY":"Khỉ",
      "SHEEP":"Cừu,",
      "CHICKEN":"Gà,",
      "DOG":"Chó,",
      "PIG":"Lợn,",
      "RED":"Đỏ",
      "BLUE":"Xanh dương ",
      "GREEN":"Xanh lá cây"
    }
    var    translationsZH_HANS = {
        "HEAD_TITLE": "壹比分觸屏版",
        "LOTTERY_RESULTS": "開獎結果",
        "HOT_LOTTERY": "熱門彩種",
        "HIGH_LOTTERY": "高頻彩",
        "LOW_LOTTERY": "低频彩",
        "NO":"第",
        "PERIOD": "期",
        "CONFIRM": '確定',
        'CANCEL': '取消',
        'FILTITLE': '定製彩種',
        'HAVEFILTITLE': '已定製彩種',
        "LOTTERY_TITLE": "彩票開獎",
        "CLICK_FIL": '點擊定製更多彩種',
        "HONGKONG_LOTTERY": "香港開獎",
        "SEVEN_COLOR": "七星彩",
        "SEVEN_COLOR_MARK": "每週二、五、日晚20:30開獎",
        "CHONGQING_CONSTANTCOLOR": "重慶時時彩",
        "CHONGQINGCONSTANTCOLOR_MARK": "白天72期，10分鐘一期；晚上48期，5分鐘一期",
        "BEIJING_CAR_RACING": "北京賽車",
        "BEIJINGCARRACING_MARK":"每天179期，5分鐘一期，9:00~00:00",
        "BEIJING_HAPPY_EI": "北京快樂八",
        "GUANGDONG_HAPPY_TEN": "廣東快樂十分",
        "GUANGDONGHAPPYTEN_MARK": "每天84期，10分鐘一期，9:00~23:00",
        "CHONGQING_LUCKY_FARM": "重慶幸運農場",
        "CHONGQINGLUCKYFARM_MARK": "每天97期，10分鐘一期，0:00~2:00 10:00~0:00",
        "JIANGXI_CONSTANTCOLOR": "江西時時彩",
        "JIANGXICONSTANTCOLOR_MARK": "每天84期，10分鐘一期，9:00~23:00",
        "XIJIANG_CONSTANTCOLOR": "新疆時時彩",
        "XIJIANGCONSTANTCOLOR_MARK": "每天96期，10分鐘一期，10:00~2:00",
        "HUNAN_HAPPY_TEN": "湖南快樂十分",
        "HUNANHAPPYTEN_MARK": "每天84期，10分鐘一期，9:00~23:00",
        "YUNNAN_CONSTANTCOLOR": "雲南時時彩",
        "YUNNANCONSTANTCOLOR_MARK": "每天72期，10分鐘一期，10:00~21:50",
        "TIANJIN_CONSTANTCOLOR": "天津時時彩",
        "TIANJINCONSTANTCOLOR_MARK": "每天84期，10分鐘一期，9:00~23:00",
        "GUANGDONG_ElevenChooseFive": "廣東十一選五",
        "GUANGDONGElevenChooseFive_MARK": "每天84期，10分鐘一期，9:00~23:00",
        "JIANGSHU_ElevenChooseFive": "江蘇十一選五",
        "JIANGSHUElevenChooseFive_MARK": "每天82期，10分鐘一期，8:30~22:10",
        "SHANDONG_ElevenChooseFive": "山東十一選五",
        "SHANDONGElevenChooseFive_MARK": "每天78期，10分鐘一期，9:00~22:00",
        "HUBEI_ElevenChooseFive": "湖北十一選五",
        "LIAONING_ElevenChooseFive": "遼寧十一選五",
        "JIANGXI_ElevenChooseFive": "江西十一選五",
        "ANHUI_FASTTHREE": "安徽快3",
        "ANHUIFASTTHREE_MARK": "每天80期，10分鐘一期，8:30~22:00",
        "GUANGXI_FASTTHREE": "廣西快3",
        "GUANGXIFASTTHREE_MARK": "每天78期，10分鐘一期，9:30~22:30",
        "JIANGSHU_FASTTHREE": "江蘇快3",
        "JIANGSHUFASTTHREE_MARK": "每天82期，10分鐘一期，8:30~22:00",
        "JILIN_HAPPY_THREE": "吉林快3",
        "CONSTANT_HAPPY": "時時樂",
        "SUM": "總分",
        "SUM_MAX": "總分大小",
        "SUM_TYPE": "總分單雙",
        "DRAGON_TRIGER": "龍虎",
        "SPEC_MAX": "特碼大小",
        "SPEC_TYPE": "特碼單雙",
        "SPEC_COLOR": "特碼波色",
        "SUM_LAST_MAX": "總和尾數大小",
        "SUM_RESULT": "和值",
        "SUM_NUM": "和值大小",
        "SUM_SINGLE": "和值單雙",
        "SUM_WEI": "和尾大小",
        "CHAMPION": "冠軍",
        "SECOND": "亞軍",
        "CHAMPION_SUM": "冠亞和大小",
        "CHAMPION_TYPE": "冠亞和單雙",
        "TIME_COUNT_DOWN": "開獎倒計時",
        "OPENING": "正在開獎中...",
        "LOADING": "加載中",
        "ONLOADING": "拼命加載中...",
        "SCOLL_PAGE": "頁面下拉自動加載內容",
        "NO_DATA": "已無更多彩果",
        "NO_CHOICE":"用戶沒有定制彩種",
        "SMALL": "小",
        "BIG": "大",
        "SINGLE": "單",
        "DOUBLE": "雙",
        "EQUALS": "和",
        "DRAGON": "龍",
        "TIGER": "虎",
        "RAT": "鼠",
        "CATTLE": "牛",
        "RABBIT": "兔",
        "SNAKE": "蛇",
        "HORSE": "馬",
        "MONKEY": "猴",
        "SHEEP": "羊",
        "CHICKEN": "雞",
        "DOG": "狗",
        "PIG": "豬",
        "RED": "紅",
        "BLUE": "藍",
        "GREEN": "綠"
    }

    $translateProvider.translations('zh', translationsZH);
    $translateProvider.translations('zh-TW', translationsZH_HANS);
    $translateProvider.translations('en',translationsEN);
     $translateProvider.translations('th',translationsTH);
   $translateProvider.translations('vi',translationsVI);
    $translateProvider.registerAvailableLanguageKeys(['zh', 'zh-TW','en','th','vi'], {
      'zh_CN': 'zh',
      'zh_TW': 'zh-TW',
      'zh_HK': 'zh-TW',
      'en_US': 'en',
      'th_TH':'th',
      'vi_VI':'vi'
    });

    $translateProvider.useSanitizeValueStrategy(null);
    // try to find out preferred language by yourself
    //$translateProvider.determinePreferredLanguage();
    var language = window.localStorage.getItem("language");
    if (language == null) {
        language = defaultLanguageKey;
    }
    $translateProvider.preferredLanguage(language);
}])
  .config(commonHeaderNav);
